import { Accordion, AccordionContent, AccordionItem, AccordionTrigger } from "../ui/accordion";

const faqs = [
  {
    question: "What is ThesisAI?",
    answer: "ThesisAI is an AI-powered academic writing assistant designed to help students and researchers in the Philippines with their thesis, dissertation, or capstone projects. It provides tools for brainstorming, outlining, drafting, citing, and checking for originality.",
  },
  {
    question: "Do you write my thesis for me? Is this a ghostwriting service?",
    answer: "No, absolutely not. Think of ThesisAI as your AI-Powered Co-Pilot. Its purpose is to assist and enhance your own writing process, not to replace it or produce a final 'AI work' for you. We do not provide ghostwriters or sell pre-written papers. Our platform is designed to help you brainstorm, structure your thoughts, improve your grammar, and check for originality, making your work easier and faster. The final work, ideas, and arguments must always be your own. We are committed to upholding academic integrity and our tools are built to empower you as a researcher, not to circumvent university policies.",
  },
  {
    question: "Who is ThesisAI for?",
    answer: "It's designed for undergraduate and graduate students working on major academic papers, as well as their thesis advisors who want to streamline the mentorship and feedback process.",
  },
  {
    question: "Is the content generated by ThesisAI original?",
    answer: "Yes. Our AI is designed to generate unique content to help you draft your work. We also provide an integrated Originality Checker to ensure your final submission is plagiarism-free and properly cited.",
  },
  {
    question: "Will my university accept a thesis written with AI assistance?",
    answer: "ThesisAI is a writing assistant, not a replacement for your own research and critical thinking. It helps with structure, grammar, and overcoming writer's block. Always follow your university's academic integrity guidelines and use the tool responsibly as a supplement to your own work.",
  },
  {
    question: "Is my research data secure and private?",
    answer: "Absolutely. We prioritize your privacy and data security. Your documents are encrypted and stored securely. We will never share your research or personal information with third parties.",
  },
];

export function FaqSection() {
  return (
    <section className="py-16 md:py-24 lg:py-32">
      <div className="container mx-auto max-w-3xl">
        <div className="mb-12 text-center">
          <h2 className="text-3xl font-bold tracking-tight sm:text-4xl">Frequently Asked Questions</h2>
        </div>
        <Accordion type="single" collapsible className="w-full">
          {faqs.map((faq, index) => (
            <AccordionItem value={`item-${index}`} key={index}>
              <AccordionTrigger className="text-left">{faq.question}</AccordionTrigger>
              <AccordionContent className="text-muted-foreground">
                {faq.answer}
              </AccordionContent>
            </AccordionItem>
          ))}
        </Accordion>
      </div>
    </section>
  );
}