-- Migration: Add composite unique index on (student_id, title) for data_management_plans
-- Date: 2025-10-09
-- Purpose: Allow multiple DMPs per student by replacing single-column uniqueness on student_id
-- NOTE: This migration is idempotent and safe to re-run.

-- 1) Attempt to drop a single-column unique constraint on student_id if it exists.
--    Common name pattern generated by Postgres for unique constraint on a column is: <table>_<column>_key
ALTER TABLE IF EXISTS public.data_management_plans
  DROP CONSTRAINT IF EXISTS data_management_plans_student_id_key;

-- 2) If there is a unique index instead of a constraint, drop it as well (safe-if-not-exists).
DO $$
DECLARE
  idx_name text;
BEGIN
  SELECT indexname INTO idx_name
  FROM pg_indexes
  WHERE schemaname = 'public'
    AND tablename = 'data_management_plans'
    AND indexdef ILIKE '%(student_id)%'
    AND indexdef ILIKE '%UNIQUE%';

  IF idx_name IS NOT NULL THEN
    EXECUTE format('DROP INDEX IF EXISTS public.%I', idx_name);
  END IF;
END;
$$ LANGUAGE plpgsql;

-- 3) Create the composite unique index on (student_id, title)
CREATE UNIQUE INDEX IF NOT EXISTS uq_student_dmp
  ON public.data_management_plans (student_id, title);
