// Types for the Apps and Workflows system

// Individual step in a workflow
export interface WorkflowStep {
  id: string; // Unique ID for this step instance
  appId: string; // ID of the app to run
  name: string; // Human-readable name
  config: Record<string, unknown>; // Configuration for the app
  inputs?: Record<string, unknown>; // Input data (can come from previous steps)
  outputs?: Record<string, unknown>; // Output data (from when the step was run)
  status: 'pending' | 'running' | 'completed' | 'failed'; // Execution status
  createdAt: Date;
  completedAt?: Date;
}

// Workflow definition
export interface Workflow {
  id: string;
  name: string;
  description: string;
  projectId: string;
  userId: string;
  steps: WorkflowStep[];
  status: 'draft' | 'active' | 'completed' | 'archived';
  createdAt: Date;
  updatedAt: Date;
  lastRunAt?: Date;
}

// Predefined workflow templates
export interface WorkflowTemplate {
  id: string;
  name: string;
  description: string;
  category: 'conceptualize' | 'research' | 'write' | 'submit' | 'defense';
  steps: Array<{
    appId: string;
    name: string;
    config: Record<string, unknown>;
  }>;
}

// Project context - stores state that apps can access
export interface ProjectContext {
  id: string;
  userId: string;
  title: string;
  abstract: string;
  currentPhase: 'conceptualize' | 'research' | 'write' | 'submit' | 'defense';
  thesisDocument: string; // Current thesis content
  references: Array<{
    id: string;
    title: string;
    url?: string;
    content: string;
  }>;
  chapters: Array<{
    id: string;
    title: string;
    content: string;
    status: 'draft' | 'reviewed' | 'finalized';
  }>;
  methodology: string;
  defenseNotes: string;
  createdAt: Date;
  updatedAt: Date;
  // Additional fields generated by apps
  [key: string]: unknown;
}

// App execution result
export interface AppExecutionResult {
  stepId: string;
  appId: string;
  inputs: Record<string, unknown>;
  outputs: Record<string, unknown>;
  status: 'success' | 'error';
  error?: string;
  executedAt: Date;
}