import { Accordion, AccordionContent, AccordionItem, AccordionTrigger } from "./ui/accordion";
import { Card, CardContent, CardHeader, CardTitle } from "./ui/card";
import { BookOpenCheck, ShieldCheck, Users, Coins, GraduationCap, BrainCircuit, Settings2, MessageSquareMore, BarChart3 } from "lucide-react";

const faqCategories = [
  {
    icon: GraduationCap,
    title: "Academic Integrity & Research Ethics",
    items: [
      {
        question: "Is using AI tools like ThesisAI considered academic dishonesty?",
        answer: "No. Our platform is designed to assist in the research process, not replace it. We provide tools for brainstorming, outlining, and improving your writing—similar to how a writing tutor would help. The final work, ideas, and arguments must always be your own. We encourage you to follow your university's academic integrity guidelines."
      },
      {
        question: "Can I use the generated text directly in my thesis?",
        answer: "You can use the generated text as a starting point or inspiration, but we strongly recommend rewriting it in your own words. The AI-generated content is meant to help overcome writer's block and provide structure, not to be copied verbatim. Always ensure your final work reflects your original thinking and voice."
      },
      {
        question: "How does the Originality Checker work?",
        answer: "Our checker uses advanced algorithms to compare your text against billions of web pages. It highlights potential matches and suggests citation formats. For maximum accuracy, we recommend running checks before submission and addressing any flagged content by proper paraphrasing and citation."
      }
    ]
  },
  {
    icon: BrainCircuit,
    title: "AI Features & Functionality",
    items: [
      {
        question: "What AI model powers ThesisAI Philippines?",
        answer: "We use Google's Gemini API for our AI features. This ensures high-quality, contextually relevant assistance while maintaining fast response times. All AI interactions are processed securely through our Supabase Edge Functions."
      },
      {
        question: "Are my documents stored in the AI system?",
        answer: "No. Your documents remain securely stored in your personal database. When using AI features, only the selected text is temporarily sent to generate suggestions. We do not retain your document content in the AI system after processing."
      },
      {
        question: "How accurate are the statistical test interpretations?",
        answer: "The AI provides general guidance based on standard statistical practices. However, it's essential to verify the interpretation with your advisor or statistics professor. The tool is designed to help you understand basic concepts, not replace expert statistical consultation."
      }
    ]
  },
  {
    icon: BarChart3,
    title: "Statistical Analysis & Data Tools",
    items: [
      {
        question: "What statistical tests are available?",
        answer: "Our platform currently supports Independent Samples T-test, Pearson Correlation, and Chi-Square Test. We plan to add more tests in the future to cover a wider range of research designs."
      },
      {
        question: "How do I upload my data for analysis?",
        answer: "You can upload your data in CSV or XLSX format directly on the 'Statistical Analysis' page under the 'Data Management' tab. Once uploaded, you can select your independent and dependent variables and choose a test to run."
      },
      {
        question: "How accurate are the statistical results generated by the platform?",
        answer: "The statistical calculations are performed using industry-standard libraries (jStat) on our secure backend. While the calculations are accurate, always ensure your data meets the assumptions of the chosen test and consult with your advisor for interpretation and reporting."
      },
      {
        question: "Can I generate charts and reports from my analysis?",
        answer: "Yes! After running an analysis, you can use the 'Visualization' tab to generate simple bar charts from your data. The 'Reporting Generator' can also help you draft a formatted report of your analysis results in styles like APA 7th Edition."
      }
    ]
  },
  {
    icon: ShieldCheck,
    title: "Security & Privacy",
    items: [
      {
        question: "Is my research data secure?",
        answer: "Yes. All documents are encrypted at rest and in transit. We use industry-standard security practices with Supabase. Your research belongs to you—we will never share it with third parties without your explicit consent."
      },
      {
        question: "Do you sell user data?",
        answer: "Absolutely not. We have a strict no-data-selling policy. The only data shared is what you explicitly choose to make public (like sharing a document link). Your private documents and personal information are never sold or shared."
      },
      {
        question: "How are passwords protected?",
        answer: "We use Supabase Auth which implements modern password hashing with bcrypt. Your password is never stored in plain text. We also support secure authentication via Google OAuth to reduce password-related risks."
      }
    ]
  },
  {
    icon: Users,
    title: "Advisor & Critic Collaboration",
    items: [
      {
        question: "How do I connect with my thesis advisor?",
        answer: "You can invite your advisor through the 'Manage Advisor' section in settings. If they're registered on ThesisAI, they'll receive a notification. Otherwise, you can designate them by name and export documents for offline review. The Pro + Advisor plan enables full online collaboration."
      },
      {
        question: "What happens when I submit a document for review?",
        answer: "When you click 'Submit for Review', your document status changes to 'submitted'. Your advisor receives a notification and can access the document through their dashboard. They can then approve it, request revisions, or mark it as approved after feedback."
      },
      {
        question: "Can multiple advisors review my work?",
        answer: "Currently, you can connect with one primary advisor. For additional feedback, we recommend exporting your document and sharing it directly. Advisors can view your work if they have your public share link, but only your designated advisor can provide official feedback through the platform."
      }
    ]
  },
  {
    icon: Coins,
    title: "Pricing & Subscriptions",
    items: [
      {
        question: "What's included in the free plan?",
        answer: "The free plan includes up to 3 documents, basic AI assistance, and 10 originality checks per month. You can explore all core features and upgrade anytime to unlock unlimited documents and advanced functionality."
      },
      {
        question: "How do referral credits work?",
        answer: "Earn ₱50 when someone signs up with your code, ₱75 when they upgrade to Pro, and additional earnings when they refer others. Credits can be used to offset subscription costs or transferred to peers. Minimum balance of ₱200.00 must be maintained."
      },
      {
        question: "Can I get a refund?",
        answer: "Due to the digital nature of our service, we don't offer refunds. However, you can cancel your subscription at any time. Remaining days in your current billing cycle won't be charged again. Contact us for exceptional circumstances."
      }
    ]
  },
  {
    icon: Settings2,
    title: "Technical Support",
    items: [
      {
        question: "Why am I experiencing slow loading?",
        answer: "Slow loading may occur due to internet connectivity issues. Try refreshing the page. If problems persist, check your network connection. The platform works best with stable internet access. Offline mode allows saving drafts locally and syncing when back online."
      },
      {
        question: "How do I report a bug?",
        answer: "Use the 'Provide Feedback' link in the footer of any page. Include details about the issue, steps to reproduce, and screenshots if possible. Our team monitors these reports daily and prioritizes critical issues."
      },
      {
        question: "Does ThesisAI work on mobile devices?",
        answer: "Yes! Our responsive design works on tablets and smartphones. While the full editing experience is optimized for larger screens, you can access documents, reviews, and most features on mobile. Use landscape mode for better editing experience."
      }
    ]
  },
  {
    icon: BookOpenCheck,
    title: "University-Specific Guidance",
    items: [
      {
        question: "How do I format my paper for [University Name]?",
        answer: "Visit the University Guides section to find specific formatting requirements for major Philippine universities. Each guide includes margin specifications, font requirements, citation styles, and sample layouts. You can also use our interactive style guide to generate properly formatted citations."
      },
      {
        question: "What if my university isn't listed?",
        answer: "If your institution isn't in our database, use the 'Request to Add' feature in the University Guides section. Our team reviews submissions weekly. In the meantime, consult your university's official style manual or thesis handbook for accurate formatting."
      },
      {
        question: "How do I cite sources in APA 7th edition?",
        answer: "Use our Citation Manager to generate and save properly formatted citations. The tool follows APA 7th edition guidelines for author names, publication dates, titles, and source information. Always double-check against the official APA manual for complex cases."
      }
    ]
  },
  {
    icon: MessageSquareMore,
    title: "General Questions",
    items: [
      {
        question: "Can I collaborate with classmates?",
        answer: "Direct collaboration between students isn't supported to maintain academic integrity. However, you can share non-sensitive parts of your research through public links or export sections for peer feedback. Remember to avoid sharing entire drafts that might compromise originality."
      },
      {
        question: "How often should I save my work?",
        answer: "Your work is automatically saved every few seconds. However, we recommend manually saving important milestones. The autosave feature ensures minimal data loss, but regular manual saves provide peace of mind during extensive writing sessions."
      },
      {
        question: "Is there a mobile app?",
        answer: "Currently, ThesisAI is web-based and accessible through any browser. A dedicated mobile app is planned for future development. The responsive web interface works well on mobile devices, though we recommend using desktop for intensive writing tasks."
      }
    ]
  }
];

export function FaqSection() {
  return (
    <section className="py-12 md:py-16 bg-slate-800">
      <div className="container mx-auto max-w-4xl px-4">
        <div className="mb-12 text-center">
          <h2 className="text-3xl font-bold tracking-tight sm:text-4xl text-white">Comprehensive FAQ</h2>
          <p className="mt-4 text-slate-300">
            Find answers to common questions about using ThesisAI Philippines
          </p>
        </div>

        <div className="space-y-8">
          {faqCategories.map((category) => (
            <Card key={category.title} className="bg-slate-900 border-slate-700">
              <CardHeader className="border-b border-slate-700">
                <div className="flex items-center gap-3">
                  <category.icon className="w-6 h-6 text-blue-400" />
                  <CardTitle className="text-xl text-white">{category.title}</CardTitle>
                </div>
              </CardHeader>
              <CardContent className="pt-6">
                <Accordion type="single" collapsible>
                  {category.items.map((faq, index) => (
                    <AccordionItem 
                      value={`item-${category.title}-${index}`} 
                      key={`${category.title}-${index}`}
                      className="border-b border-slate-700"
                    >
                      <AccordionTrigger className="text-left text-base font-medium text-white hover:no-underline">
                        {faq.question}
                      </AccordionTrigger>
                      <AccordionContent className="text-base text-slate-300 pt-2 pb-4">
                        {faq.answer}
                      </AccordionContent>
                    </AccordionItem>
                  ))}
                </Accordion>
              </CardContent>
            </Card>
          ))}
        </div>
      </div>
    </section>
  );
}