import { Accordion, AccordionContent, AccordionItem, AccordionTrigger } from "./ui/accordion";

const faqs = [
  {
    question: "What is ThesisAI?",
    answer: "ThesisAI is an AI-powered academic writing assistant designed to help students and researchers in the Philippines with their thesis, dissertation, or capstone projects. It provides tools for brainstorming, outlining, drafting, citing, and checking for originality.",
  },
  {
    question: "Do you write my thesis for me? Is this a ghostwriting service?",
    answer: "No, absolutely not. Think of ThesisAI as your AI-Powered Co-Pilot. Its purpose is to assist and enhance your own writing process, not to replace it or produce a final 'AI work' for you. We do not provide ghostwriters or sell pre-written papers. Our platform is designed to help you brainstorm, structure your thoughts, improve your grammar, and check for originality, making your work easier and faster. The final work, ideas, and arguments must always be your own. We are committed to upholding academic integrity and our tools are built to empower you as a researcher, not to circumvent university policies.",
  },
  {
    question: "Who is ThesisAI for?",
    answer: "It's designed for undergraduate and graduate students working on major academic papers, as well as their thesis advisors who want to streamline the mentorship and feedback process.",
  },
  {
    question: "How do I connect with my advisor and manuscript critic?",
    answer: "You are responsible for connecting with your thesis advisor and manuscript critic. The platform does not assign these roles for you. You can invite your advisor or critic through the 'Manage Advisor' and 'Manage Critic' sections in your settings. If they are registered on ThesisAI, you can send them an invitation directly. If not, you can designate them by name in the system and export your work for offline review. The Pro + Advisor plan allows you to connect with one online advisor, while the Manuscript Critic service enables collaboration with a professional reviewer for final editing certification.",
  },
  {
    question: "Is the content generated by ThesisAI original?",
    answer: "Yes. Our AI is designed to generate unique content to help you draft your work. We also provide an integrated Originality Checker to ensure your final submission is plagiarism-free and properly cited.",
  },
  {
    question: "Will my university accept a thesis written with AI assistance?",
    answer: "ThesisAI is a writing assistant, not a replacement for your own research and critical thinking. It helps with structure, grammar, and overcoming writer's block. Always follow your university's academic integrity guidelines and use the tool responsibly as a supplement to your own work.",
  },
  {
    question: "Is my research data secure and private?",
    answer: "Absolutely. We prioritize your privacy and data security. Your documents are encrypted and stored securely. We will never share your research or personal information with third parties.",
  },
  {
    question: "I'm struggling to find a good research topic. Can you help?",
    answer: "Yes! Use our Topic Idea Generator to get three unique and researchable thesis topics based on your field of study. While we can't show what has already been studied at your institution (due to privacy), our AI generates suggestions that balance feasibility with originality within the Philippine academic context.",
  },
  {
    question: "How can I reduce feelings of isolation during my research?",
    answer: "We understand how challenging research can be when done alone. While we don't have direct peer matching yet, our Resources section includes productivity tips like the Pomodoro Technique and setting realistic daily goals to help manage workload. We're also exploring ways to create safe, moderated communities where students can share experiences without compromising academic integrity.",
  },
  {
    question: "Can ThesisAI help prevent burnout?",
    answer: "While we can't replace mental health professionals, our platform helps reduce stress by streamlining the research process. Features like the Session Goal Card encourage manageable daily tasks rather than overwhelming word count targets. The Thesis Checklist breaks down the entire project into smaller steps, helping you track progress and maintain momentum. For serious concerns, we recommend seeking support from your institution's counseling services.",
  },
  {
    question: "Why should I trust your citation manager?",
    answer: "Our citation tools are designed to minimize errors by providing clear examples and templates. However, we emphasize that you should always verify citations against your university's official style guide. No automated tool can catch every nuance, so we encourage using our Citation Manager as a starting point followed by careful manual verification.",
  }
];

export function FaqSection() {
  return (
    <section className="py-12 md:py-16 bg-slate-800">
      <div className="container mx-auto max-w-3xl">
        <div className="mb-12 text-center">
          <h2 className="text-3xl font-bold tracking-tight sm:text-4xl text-white">Frequently Asked Questions</h2>
        </div>
        <Accordion type="single" collapsible className="w-full">
          {faqs.map((faq, index) => (
            <AccordionItem value={`item-${index}`} key={index} className="border-b-slate-700">
              <AccordionTrigger className="text-left text-lg font-medium text-white hover:no-underline">{faq.question}</AccordionTrigger>
              <AccordionContent className="text-base text-slate-300 pt-2">
                {faq.answer}
              </AccordionContent>
            </AccordionItem>
          ))}
        </Accordion>
      </div>
    </section>
  );
}