// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

// Get environment variables with fallbacks
const SUPABASE_URL = process.env.NEXT_PUBLIC_SUPABASE_URL || '';
const SUPABASE_PUBLISHABLE_KEY = process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY || '';

// Check if we have valid configuration
const hasValidConfig = SUPABASE_URL && SUPABASE_PUBLISHABLE_KEY && SUPABASE_URL !== '' && SUPABASE_PUBLISHABLE_KEY !== '';

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = hasValidConfig
  ? createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
      auth: {
        // Configure session storage with fallback
        storage: typeof window !== 'undefined' ? window.localStorage : undefined,
        autoRefreshToken: true,
        persistSession: true,
        detectSessionInUrl: true,
      },
    })
  : (null as any); // Will be handled by the supabaseWithFallback function

// Enhanced function with fallback and error handling
export async function supabaseWithFallback<T>(
  operation: () => Promise<{ data: T | null; error: any }>,
  fallbackValue: T | null = null,
  operationName: string = 'Supabase operation'
): Promise<{ data: T | null; error: any }> {
  // Check if configuration is valid
  if (!hasValidConfig) {
    console.warn(`[Supabase] Configuration missing for ${operationName}, returning fallback`);
    return { data: fallbackValue, error: new Error(`Supabase not configured: ${operationName}`) };
  }

  try {
    const result = await operation();
    if (result.error) {
      console.error(`[Supabase] ${operationName} failed:`, result.error);
      return { data: result.data, error: result.error };
    }
    return result;
  } catch (error: any) {
    console.error(`[Supabase] ${operationName} threw error:`, error);
    return { data: fallbackValue, error };
  }
}

export function getSupabaseFunctionUrl(functionName: string): string {
  if (!hasValidConfig) {
    console.warn(`[Supabase] Configuration missing for function URL: ${functionName}`);
    return '';
  }
  return `${SUPABASE_URL}/functions/v1/${functionName}`;
}

// Export createClient function as well
export { createClient };